pipeline {
  agent {
    kubernetes {
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
"""
    }  stages {
    stage('Test feature branch') {
      when {
        not { branch 'master'
          }
        }
      steps {
     container('maven') {
        sh """
        mvn test -Dcucumber.options="--tags @${env.BRANCH_NAME}"
        """
        }
      }
    }
    stage('Test master branch') {
      steps {
     container('maven') {
        sh """
        mvn test -Dcucumber.options="--tags @master"
        """
        }
      }
    }
  }
}
